language: node_js
sudo: false
node_js:
  - '0.10'
before_install:
  - "mkdir ~/.npm"
install:
  - npm install
  - npm install git://github.com/hybridgroup/cylon.git
  - npm install -g jshint istanbul codeclimate-test-reporter
script:
  - make ci
  - CODECLIMATE_REPO_TOKEN=51cae3eaf9b1790b956a71dcf02cc4e1f05425fbd4d2f09de6b521f01490d739 codeclimate < coverage/lcov.info
